// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAouArYl3iIWMXpt0QNw_K6eYXj3BEzemk',
    appId: '1:1071956687809:android:b8d0ed9620060224dccd40',
    messagingSenderId: '1071956687809',
    projectId: 'e-commerce-app-ce1a6',
    storageBucket: 'e-commerce-app-ce1a6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfrLvnt2V6h0PH8e_50meYHNnkxODgOCc',
    appId: '1:1071956687809:ios:943a89c1e4361151dccd40',
    messagingSenderId: '1071956687809',
    projectId: 'e-commerce-app-ce1a6',
    storageBucket: 'e-commerce-app-ce1a6.firebasestorage.app',
    iosClientId: '1071956687809-qs4fapfn7n650b2977q8db2sfbqqpqbk.apps.googleusercontent.com',
    iosBundleId: 'com.example.eCommerceApplication',
  );
}
